jobs/urls.py
from django.urls import path

from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.home, name='home'),
    path('job/<int:pk>', views.job_detail, name='job_detail'),
]

portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/models.py
from django.db import models

class Job(models.Model):
    image = models.ImageField(upload_to='images/')
    summary = models.CharField(max_length=250)
    objects = models.Manager()

    def __str__(self):
        return self.summary

jobs/views.py
from django.shortcuts import render, get_object_or_404
from .models import Job


def home(request):
    jobs = Job.objects.all()
    context = {
        'jobs' : jobs
    }
    return render(request, 'jobs/index.html', context)


def job_detail(request, pk):
    job = get_object_or_404(Job, pk=pk)
    context = {
        'job': job
    }
    return render(request, 'jobs/detail.html', context)

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Milson Munakami " Milstein"">
    <meta name="generator" content="Jekyll v3.8.6">

    <title>
        {% block title %}
        {% endblock title%}
    </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/album/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'jobs/css/bootstrap.min.css' %}">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->


    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
    <meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <!-- <link href="album.css" rel="stylesheet"> -->
</head>

<body>

    <!-- Navbar -->
    <nav>

    </nav>
    <!-- Navbar ends -->
    <br />

    {% include 'jobs/partials/_message.html' %}

    <main role="main">

        <!-- Main Section -->
        {% block  content %}
        {% endblock content %}
        <!-- Main Section ends-->

    </main>

    <footer class="text-muted mt-4 mb-4">
        <p class="text-center p-1 m-0">&copy; Milstein's Portfolio 2020</p>
    </footer>

    <script src="{% static 'jobs/js/jquery-3.5.0.min.js' %}">
    </script>
    <script src="{% static 'jobs/js/popper.min.js' %}">
    </script>
    <script src="{% static 'jobs/js/bootstrap/bootstrap.min.js' %}">
    </script>

    <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> -->
  
</body>

</html>

templates/jobs/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Job Detail: {{job.id}}
{% endblock title %}

{% block content %}

<section class="jumbotron text-center">
    <div class="container">
        <h1>Job Detail</h1>
        <p class="lead text-muted">{{ job.summary }}</p>
        {% if job.image %}<img src="{{job.image.url}}" alt="{{job.summary}}" width="100%" height="225">{% endif %}
        <p>
            <a href="{% url 'jobs:home' %}" class="btn btn-primary my-2">Back</a>
        </p>
    </div>
</section>

{% endblock content %}

templates/jobs/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
My Portfolio
{% endblock title %}

{% block content %}

<section class="jumbotron text-center">
    <div class="container">
        <h1>Milson Munakami</h1>
        <p class="lead text-muted">Hi! My name is Milstein, I enjoy making apps and websites. Also, loves making
            friends.</p>
        <p>
            <a href="mailto:milsonmun@gmail.com" class="btn btn-primary my-2">Email Me</a>
        </p>
        
        <img src="{% static 'jobs/uploads/milstein.png' %}" alt="Milstein Munakami" height="500px">
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">

        <div class="row">

            {% if jobs %}
            {% for job in jobs %}
                {% include 'jobs/partials/_card.html' %}
            {% endfor %}
            {% else %}
                <p class="d-block font-weight-light my-2 heading">You have not saved any jobs yet!</p>
            {% endif %}

        </div>
    </div>
</div>

{% endblock content %}

templates/jobs/partials/_card.html
<div class="col-md-4">
    <div class="card mb-4 shadow-sm">
        <a href="{% url 'jobs:job_detail' job.id %}">
            {% if job.image %}<img src="{{job.image.url}}" alt="{{job.summary}}" width="100%" height="225">{% endif %}
        </a>
        <div class="card-body">
            <p class="card-text"><a href="{% url 'jobs:job_detail' job.id %}">{{job.summary}}</a></p>
        </div>
    </div>
</div>

templates/jobs/partials/_message.html
{% if messages %}
{% for message in messages %}
<div class="container">
    <div class="alert {% if message.tags == 'error' %}alert-danger{% endif %}{% if message.tags == 'success' %}alert-success{% endif %} else alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
</div>
{% endfor %}
{% endif %}